// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC2zmkFkymmf3Lb5CYmdYGmLxsztNpZY5I',
    appId: '1:751385137703:web:4b95831ec5602796707402',
    messagingSenderId: '751385137703',
    projectId: 'sitecard-7a583',
    authDomain: 'sitecard-7a583.firebaseapp.com',
    storageBucket: 'sitecard-7a583.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAk_4EldV4is2W5iSkykxxy1Ho-OFNQ5ag',
    appId: '1:751385137703:android:b5e13b93ad127cb6707402',
    messagingSenderId: '751385137703',
    projectId: 'sitecard-7a583',
    storageBucket: 'sitecard-7a583.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzyWHA4z2VMMi_brcz3exG1-AJ1vRcVCE',
    appId: '1:751385137703:ios:65ca1e8299c65df1707402',
    messagingSenderId: '751385137703',
    projectId: 'sitecard-7a583',
    storageBucket: 'sitecard-7a583.firebasestorage.app',
    iosBundleId: 'com.example.sitecard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzyWHA4z2VMMi_brcz3exG1-AJ1vRcVCE',
    appId: '1:751385137703:ios:65ca1e8299c65df1707402',
    messagingSenderId: '751385137703',
    projectId: 'sitecard-7a583',
    storageBucket: 'sitecard-7a583.firebasestorage.app',
    iosBundleId: 'com.example.sitecard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC2zmkFkymmf3Lb5CYmdYGmLxsztNpZY5I',
    appId: '1:751385137703:web:a1c75002c3104a58707402',
    messagingSenderId: '751385137703',
    projectId: 'sitecard-7a583',
    authDomain: 'sitecard-7a583.firebaseapp.com',
    storageBucket: 'sitecard-7a583.firebasestorage.app',
  );
}
